# Generated by Django 4.1.5 on 2023-06-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermobile',
            old_name='user',
            new_name='uservnszdhgfhgsfgh',
        ),
    ]
