# Generated by Django 4.1.5 on 2023-06-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_user_usermobile_uservnszdhgfhgsfgh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermobile',
            old_name='uservnszdhgfhgsfgh',
            new_name='user',
        ),
    ]
