# Generated by Django 4.1.5 on 2023-06-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_to_do_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
