# Generated by Django 4.1.5 on 2023-06-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_to_do_list_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='user_name',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
