# Generated by Django 4.1.5 on 2023-06-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_to_do_list_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
